config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'
  resources :surveys do
    resources :survey_submissions, shallow: true do
    end
  end
  devise_for :users

end

app/models/survey_submission.rb
class SurveySubmission < ActiveRecord::Base
  belongs_to :survey
  has_many :survey_money_answers,   dependent: :destroy, inverse_of: :survey_submission
  has_many :survey_rating_answers,  dependent: :destroy, inverse_of: :survey_submission
  has_many :survey_openend_answers, dependent: :destroy, inverse_of: :survey_submission
  has_many :survey_questions,        through: :survey
  has_many :survey_money_questions,  through: :survey
  has_many :survey_rating_questions, through: :survey

  validates_associated :survey_money_answers,
                       :survey_rating_answers,
                       :survey_openend_answers

  accepts_nested_attributes_for :survey_money_answers,
                                :survey_openend_answers,
                                :survey_rating_answers,
                                reject_if: :all_blank,
                                allow_destroy: true

  validates :survey, presence: true

  validate :submission_costs_less_than_max_budget

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {scope: :survey}, format: VALID_EMAIL_REGEX

  def submission_spending
    begin
      self.survey_money_answers.map(&:dollar).sum
    rescue
      0
    end
  end

  def submission_avg_rating
    begin
      self.survey_rating_answers.average(:value)
    rescue
      0
    end
  end

  def chart_money_datum
    {
      labels: self.survey_money_questions.pluck(:title),
      datasets:[
          {
              label: "Submissions Average",
              fillColor: "rgba(179,181,198,0.2)",
              strokeColor: "rgba(179,181,198,1)",
              pointColor: "rgba(179,181,198,1)",
              pointStrokeColor: "#fff",
              pointHightlightFill: "#fff",
              pointHightlightStroke: "rgba(179,181,198,1)",
              data: self.survey_money_answers.pluck(:dollar)
          }
      ]
    }.to_json
  end

  private

    def submission_costs_less_than_max_budget
      if self.submission_spending > self.survey.max_budget
        errors.add(:spending, "Your plan must cost less than the maximum budget")
      end
    end

end

app/controllers/survey_submissions_controller.rb
class SurveySubmissionsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :show]
  before_action :set_survey_submission, only: [:show, :edit, :update, :destroy]
  before_action :set_survey, only: [:new, :create, :index]

  # GET /survey_submissions
  # GET /survey_submissions.json
  def index
    @survey_submissions = SurveySubmission.where(survey: params["survey_id"])

    @answers_histogram_data = @survey.chart_histogram_data
    @radar_data = @survey.chart_average_dollar_data
    @chart_rating_average = @survey.chart_average_rating_data
  end

  # GET /survey_submissions/1
  # GET /survey_submissions/1.json
  def show
  end

  # GET /survey_submissions/new
  def new
    @survey_submission = SurveySubmission.new
    @survey_submission.survey = @survey
    @survey.survey_questions.each do |qu|
      @survey_submission.public_send(qu.answers_type)
                        .build("#{qu.question_type}_id".to_sym => qu.id)
    end
  end

  # GET /survey_submissions/1/edit
  def edit
  end

  # POST /survey_submissions
  # POST /survey_submissions.json
  def create
    @survey_submission = SurveySubmission.new(survey_submission_params)
    @survey_submission.survey = @survey

    respond_to do |format|
      if @survey_submission.save
        format.html { redirect_to @survey_submission, notice: 'Thanks for your input!' }
        format.json { render :show, status: :created, location: @survey_submission }
      else
        format.html { render :new }
        format.json { render json: @survey_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_submissions/1
  # PATCH/PUT /survey_submissions/1.json
  def update
    respond_to do |format|
      if @survey_submission.update(survey_submission_params)
        format.html { redirect_to @survey_submission, notice: 'Survey submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_submission }
      else
        format.html { render :edit }
        format.json { render json: @survey_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_submissions/1
  # DELETE /survey_submissions/1.json
  def destroy
    @survey_submission.destroy
    respond_to do |format|
      format.html { redirect_to survey_survey_submissions_path @survey_submission.survey, notice: 'Survey submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_submission
      @survey_submission = SurveySubmission.find(params[:id])
    end

    def set_survey
      @survey = Survey.find(params[:survey_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_submission_params
      params.require(:survey_submission).permit(:email,
                                                :is_local,
                                                :age_range,
                                                :comment,
                                                survey_money_answers_attributes: [
                                                            :dollar,
                                                            :id,
                                                            :survey_money_question_id,
                                                            :_destroy ],
                                                survey_rating_answers_attributes: [
                                                            :value,
                                                            :id,
                                                            :survey_rating_question_id,
                                                            :_destroy ],
                                                survey_openend_answers_attributes: [
                                                            :thought,
                                                            :id,
                                                            :survey_openend_question_id,
                                                            :_destroy ] )
    end
end

app/helpers/survey_submissions_helper.rb
module SurveySubmissionsHelper
end

app/views/survey_submissions/_form.html.erb
<%= javascript_tag do %>
    window.max_budget = <%= @survey_submission.survey.max_budget %>
<% end %>

<h1 class="page-header"><%= @survey_submission.survey.title %></h1>

<%= simple_form_for([@survey, @survey_submission]) do |f| %>
  <%= f.error_notification %>
  <% if @survey_submission.survey.budgeting? %>
    <p>
      <strong>The plan maximum budget is</strong>
      <span id="max_budget"><%= number_to_currency(@survey_submission.survey.max_budget, precision: 0) %></span>
    </p>

    <div id="submission_spending_bar" class="progress">
      <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
        <p>
          <strong>Your plan costs</strong>
          <span id="submission_spending_value"></span>
        </p>
      </div>
    </div>
  <% end %>



  <div class="has-error"><%= f.error :spending %></div>

  <div class="survey_money_answers container">
    <%= f.simple_fields_for :survey_money_answers do |response| %>
      <%= render "survey_money_answer_fields", f: response %>
    <% end %>
  </div>
  <div class="survey_openend_answers container">
    <%= f.simple_fields_for :survey_openend_answers do |response| %>
      <%= render "survey_openend_answer_fields", f: response %>
    <% end %>
  </div>
  <div class="survey_rating_answers container">
    <%= f.simple_fields_for :survey_rating_answers do |response| %>
      <%= render "survey_rating_answer_fields", f: response %>
    <% end %>
  </div>

  <div class="form-inputs">
    <h2>Thank You!</h2>
    <h4>Please, give us some information about yourself.</h4>
    <%= f.input :email %>
    <label class="control-label">Do you live in the community?</label>
    <%= f.collection_radio_buttons :is_local, [[true, 'Yes'] ,[false, 'No']], :first, :last, class: "radio-inline" %>
    <%= f.input :age_range, collection: @survey_submission.survey.AGE_RANGE_CHOICES %>
    <%= f.input :comment, label: "Share any additional thoughts here." %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit" %>
  </div>
<% end %>

app/views/survey_submissions/_survey_money_answer_fields.html.erb
<div class='nested-fields row'>

  <h2><%= f.object.survey_money_question.try(:title) || "Untitled" %></h2>
  <%= f.input :survey_money_question_id, as: :hidden %>
  <div class="form-inputs col-md-6">
    <div class="row">
      <%= f.input :dollar, label: false, input_html: { class: "dollar_answer slider_answer",
        "data-slider-id": "default-slider",
        "data-slider-min": f.object.survey_money_question.min,
        "data-slider-max": f.object.survey_money_question.max,
        "data-slider-step": f.object.survey_money_question.step,
        "data-slider-ticks": f.object.survey_money_question.tick(:value),
        "data-slider-ticks-labels": f.object.survey_money_question.tick(:label),
        "data-slider-ticks-snap-bounds": f.object.survey_money_question
                                          .survey_question_ticks.maximum(:value) || nil,
        "data-slider-tooltip": "show"
        # "data-slider-value is hidding in
        # bootstrap-slider's javascript(.slider())"
        } %>
    </div>
    <div class="row">
      <div class="slider-min col-xs-2 text-left">
        <%= number_to_currency(f.object.survey_money_question.min_value, precision: 0) %>
      </div>
      <div class="slider-max col-xs-2 col-xs-offset-8 text-right">
        <%= number_to_currency(f.object.survey_money_question.max_value, precision: 0) %>
      </div>
    </div>
  </div>
  <p class="col-md-6 text-justify">
    <%= f.object.survey_money_question.try(:body) %>
  </p>

  <hr>
</div>

app/views/survey_submissions/_survey_openend_answer_fields.html.erb
<div class='nested-fields row'>
  <h2><%= f.object.survey_question.try(:title) || "Untitled" %></h2>
  <%= f.input :survey_openend_question_id, as: :hidden %>
  <div class="form-inputs col-md-6">
    <%= f.input :thought, label: false %>
  </div>
  <p class="col-md-6 text-justify">
    <%= f.object.survey_question.try(:body) %>
  </p>

  <hr>
</div>

app/views/survey_submissions/_survey_rating_answer_fields.html.erb
<div class='nested-fields row'>

  <h2><%= f.object.survey_rating_question.try(:title) || "Untitled" %></h2>
  <%= f.input :survey_rating_question_id, as: :hidden %>
  <div class="form-inputs col-md-6">
    <div class="row">
      <%= f.input :value, label: false, input_html: { class: "value_answer slider_answer",
        "data-slider-id": "default-slider",
        "data-slider-min": f.object.survey_rating_question.min,
        "data-slider-max": f.object.survey_rating_question.max,
        "data-slider-step": f.object.survey_rating_question.step,
        "data-slider-ticks": f.object.survey_rating_question.tick(:value),
        "data-slider-ticks-labels": f.object.survey_rating_question.tick(:label),
        "data-slider-ticks-snap-bounds": f.object.survey_rating_question
                                          .survey_question_ticks.maximum(:value) || nil,
        "data-slider-tooltip": "show"
        # "data-slider-value is hidding in
        # bootstrap-slider's javascript(.slider())"
        } %>
    </div>
  </div>
  <p class="col-md-6 text-justify">
    <%= f.object.survey_rating_question.try(:body) %>
  </p>

  <hr>
</div>

app/views/survey_submissions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @survey_submission %> |
<%= link_to 'Completed Surveys', survey_survey_submissions_path(@survey_submission.survey) if user_signed_in? %> |
<%= link_to 'All Surveys', survey_survey_submissions_path(@survey_submission.survey)%>

app/views/survey_submissions/index.html.erb
<% bar_size = { height: 500, width: 500} %>
<% radar_size = { height: 500, width: 500} %>

<p id="notice"><%= notice %></p>

<h1><strong><%= @survey.title %></strong></h1>

<div class="page-header">
  <h3>Spending Overview</h3>
</div>

<% if @survey.budgeting? %>
  <div class="panel panel-default">
    <div class="panel-heading"><h3>Average Spending</h3></div>
    <div class="panel-body text-center">
      <%= radar :radar_chart, radar_size, @radar_data %>
      <p>
        <Strong>The average plan costs</Strong>
        <%= number_to_currency @survey.average_spending, precision: 0 %>
      </p>
    </div>
  </div>
<% end %>

<% if @survey.rating? %>
  <div class="panel panel-default">
    <div class="panel-heading"><h3>Average Rating</h3></div>
    <div class="panel-body text-center">
      <%= bar :rating_chart, bar_size, @chart_rating_average %>
      <p><Strong>The average rating was</Strong>
        <%= number_with_precision @survey.average_rating, precision: 1 %>
      </p>
    </div>
  </div>
<% end %>

<div class="page-header">
  <h3>Disaggregated Frequency Charts</h3>
</div>
<div class="container">
  <% @answers_histogram_data.each do |question_record, chart_json| %>
  <div class="col-md-6">
    <div class="panel panel-default">
    <h4 class="panel-heading">
      <strong><%= question_record.title %></strong>
      <%= question_record.type.titleize %> Component
    </h4>
    <div class="panel-body text-center"><%= bar question_record.id, bar_size, chart_json %></div>
  </div>
</div>
  <% end %>
</div>

<div class="page-header">
  <h3>Individual Submissions</h3>
</div>
<table>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>Plan Cost</th>
      <th>Plan Average Rating</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_submissions.each do |survey_submission| %>
      <tr>
        <td><%= survey_submission.id %></td>
        <td><%= survey_submission.email || "" %></td>
        <td><%= number_to_currency survey_submission.submission_spending, precision: 0 %></td>
        <td><%= number_with_precision survey_submission.submission_avg_rating, precision: 1 %></td>
        <td class="col-sm-2 text-right">
          <span><%= link_to 'Show', survey_submission %> |</span>
          <span><%= link_to 'Edit', edit_survey_submission_path(survey_submission) %> |</span>
          <span><%= link_to 'Delete', survey_submission, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Take', new_survey_survey_submission_path %> |
<%= link_to 'Show Survey', @survey %> |
<%= link_to 'All Surveys', surveys_path %>

app/views/survey_submissions/new.html.erb
<%= render 'form' %>

<% if user_signed_in?  %>
  <%= link_to 'Show Survey', @survey_submission.survey %> |
  <%= link_to 'Edit Survey', edit_survey_path(@survey_submission.survey) %> |
  <%= link_to 'Completed Surveys', survey_survey_submissions_path(@survey_submission.survey) %>
<% end %>

app/views/survey_submissions/show.html.erb
<% chart_size = { height: 500, width: 500} %>

<p id="notice"><%= notice %></p>

<div>
  <h2><%= @survey_submission.survey.title %></h2>
  <div>
    <p><Strong>Submitted by</Strong> <%= @survey_submission.email || "Unknown" %></p>
  </div>
</div>

<div id="submitted_survey">
  <p><Strong>Your plan costs</Strong> <%= number_to_currency(@survey_submission.submission_spending, precision: 0) %></p>

  <h4>Spending Profile</h4>
  <%= radar :radar_chart, chart_size, @survey_submission.chart_money_datum %>

  <% @survey_submission.survey_money_answers.each do |response| %>
    <h4><%= response.survey_question.title %></h4>
    <p><%= response.survey_question.body %></p>
    <div class="survey_questions">
      <h4><%= number_to_currency(response.dollar) %></h4>
    <div>
    <hr/>
  <% end %>
  <% @survey_submission.survey_openend_answers.each do |response| %>
    <h4><%= response.survey_question.title %></h4>
    <p><%= response.survey_question.body %></p>
    <div class="survey_questions">
      <h4><%= response.thought %></h4>
    <div>
    <hr/>
  <% end %>
  <% @survey_submission.survey_rating_answers.each do |response| %>
    <h4><%= response.survey_question.title %></h4>
    <p><%= response.survey_question.body %></p>
    <div class="survey_questions">
      <h4><%= response.value %></h4>
    <div>
    <hr/>
  <% end %>
</div>

<% if user_signed_in?  %>
  <%= link_to 'Edit Submission', edit_survey_submission_path(@survey_submission) %> |
  <%= link_to 'Show Survey', @survey_submission.survey %> |
  <%= link_to 'Edit Survey', edit_survey_path(@survey_submission.survey) %> |
  <%= link_to 'Completed Surveys', survey_survey_submissions_path(@survey_submission.survey) %>
<% end %>