config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'
  resources :surveys do
    resources :survey_submissions, shallow: true do
    end
  end
  devise_for :users

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  require 'histogram/array'  # enables Array#histogram
  HISTOGRAM_BIN_SIZE = 5

  belongs_to :user
  has_many :survey_questions, dependent: :destroy, inverse_of: :survey
  has_many :survey_submissions, dependent: :destroy, inverse_of: :survey
  has_many :survey_money_questions, dependent: :destroy, inverse_of: :survey
  has_many :survey_money_answers, through: :survey_submissions
  has_many :survey_rating_questions, dependent: :destroy, inverse_of: :survey
  has_many :survey_rating_answers, through: :survey_submissions
  has_many :survey_openend_questions, dependent: :destroy, inverse_of: :survey
  has_many :survey_openend_answers,   through: :survey_submissions

  validates_associated          :survey_money_questions,
                                :survey_openend_questions,
                                :survey_questions

  accepts_nested_attributes_for :survey_money_questions,
                                :survey_openend_questions,
                                :survey_rating_questions,
                                reject_if: :all_blank,
                                allow_destroy: true

  validates :title, presence: true
  validates :user, presence: true
  validates :max_budget, numericality: { only_integer: true }, allow_nil: true
  validate :max_budget_if_questions_exist

  def budgeting?
    self.survey_money_answers.any?
  end

  def rating?
    self.survey_rating_answers.any?
  end

  def range_values_for(question)
    question.try(:survey_money_answers).try(:pluck, :dollar) ||
      question.try(:survey_rating_answers).try(:pluck, :value)
  end

  def chart_histogram_data
    histogram = {}
    self.survey_questions.where("type = 'SurveyMoneyQuestion' or type = 'SurveyRatingQuestion'").each do |qu|
      chart_data = range_values_for qu
      (bins, freqs) = chart_data.histogram(HISTOGRAM_BIN_SIZE)
      begin
        bins.map!(&:truncate)
      rescue
        puts "The chart labels could not be truncated. Check for nils in answers for survey #{self.id}"
      end
      histogram[qu] = chart_datum(labels: bins, label: bins, data: freqs).to_json
    end
    histogram
  end

  def chart_average_dollar_data
    question_labels = []
    average_data = []
    self.survey_money_questions.each do |qu|
      question_labels << qu.title
      average_data << qu.survey_money_answers.average(:dollar)
    end
    chart_datum(labels: question_labels, data: average_data).to_json
  end

  def chart_average_rating_data
    question_labels = []
    average_data = []
    self.survey_rating_questions.each do |qu|
      question_labels << qu.title
      average_data << qu.survey_rating_answers.average(:value)
    end
    chart_datum(labels: question_labels, data: average_data).to_json
  end

  def average_spending
    self.survey_money_answers.average(:dollar) || nil
  end

  def average_rating
    self.survey_money_answers.average(:dollar) || nil
  end

  def AGE_RANGE_CHOICES
    [ "< 18", "18 – 24", "25 – 35", "35 – 44", "44 – 54", "> 55" ]
  end

  private

    def chart_datum(labels: nil, data: nil, label: "Submissions Average")
      {
        labels: labels,
        datasets:[
            {
                label: label,
                fillColor: "rgba(179,181,198,0.2)",
                strokeColor: "rgba(179,181,198,1)",
                pointColor: "rgba(179,181,198,1)",
                pointStrokeColor: "#fff",
                pointHightlightFill: "#fff",
                pointHightlightStroke: "rgba(179,181,198,1)",
                data: data
            }
        ]
      }
    end

    def max_budget_if_questions_exist
      if self.max_budget.nil? && self.survey_money_questions.any?
        errors.add(:max_budget, "Including budget questions requires a maximum to be set")
      end
    end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @survey.survey_money_questions.build
    @survey.survey_openend_questions.build
    @survey.survey_rating_questions.build
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    @survey.user = current_user

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:title, :max_budget,
                                      survey_money_questions_attributes:
                                        [ :title,
                                          :body,
                                          :min,
                                          :max,
                                          :step,
                                          :id,
                                          :_destroy,
                                          { survey_question_ticks_attributes:
                                              [ :value,
                                                :label,
                                                :id,
                                                :_destroy ]} ],
                                      survey_rating_questions_attributes:
                                        [ :title,
                                          :body,
                                          :min,
                                          :max,
                                          :step,
                                          :id,
                                          :_destroy,
                                          { survey_question_ticks_attributes:
                                              [ :value,
                                                :label,
                                                :id,
                                                :_destroy ]} ],
                                      survey_openend_questions_attributes:
                                        [ :title,
                                          :body,
                                          :thought,
                                          :id,
                                          :_destroy ] )
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= simple_form_for(@survey) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :title, label: "Survey title" %>
    <%= f.input :max_budget, label: "Maximum budget" %>
  </div>

  <div id="survey_questions">
    <%= f.simple_fields_for :survey_money_questions do |r| %>
      <%= render "survey_money_question_fields", f: r %>
    <% end %>

    <%= f.simple_fields_for :survey_openend_questions do |r| %>
      <%= render "survey_openend_question_fields", f: r %>
    <% end %>

    <%= f.simple_fields_for :survey_rating_questions do |r| %>
      <%= render "survey_rating_question_fields", f: r %>
    <% end %>

    <div class="links">
      <%= link_to_add_association 'add budget question |', f, :survey_money_questions %>
      <%= link_to_add_association 'add rating question |', f, :survey_rating_questions %>
      <%= link_to_add_association 'add open-ended question', f, :survey_openend_questions %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/surveys/_survey_money_question_fields.html.erb
<div class='nested-fields'>
  <h3><%= f.object.type.titleize %></h3>
  <div class="form-inputs well">
    <%= f.input :title, label: "Input component title" %>
    <%= f.input :body, label: "Input component description" %>
    <div class="row no-gutter">
      <%= f.input :min, wrapper_html: {class: "col-md-4"}, label: "Minimum value" %>
      <%= f.input :max, wrapper_html: {class: "col-md-4"}, label: "Maximum value" %>
      <%= f.input :step, wrapper_html: {class: "col-md-4"},
                                       input_html: {value: f.object.try(:step) || 1},
                                       label: "Minimum increment" %>
    </div>
    <div class="survey_question_ticks">
        <%= f.simple_fields_for :survey_question_ticks do |tick| %>
          <%= render "survey_question_tick_fields", f: tick %>
        <% end %>
        <div class="links btn-group role="group"">
          <%= link_to_add_association 'add tick', f, :survey_question_ticks,
                                              class: "btn btn-default btn-sm" %>
          <%= link_to_remove_association 'clear ticks', f,
                                              wrapper_class: '.tick_fields',
                                              class: 'btn btn-default btn-sm' %>
        </div>
    </div>
  </div>

  <%= link_to_remove_association "remove question", f, class: "btn btn-danger btn-sm" %>
  <hr>
</div>

app/views/surveys/_survey_openend_question_fields.html.erb
<div class='nested-fields'>
  <h3><%= f.object.type.titleize %></h3>
  <div class="form-inputs well">
    <%= f.input :title, label: "Input component title" %>
    <%= f.input :body, label: "Input component description" %>
  </div>

  <%= link_to_remove_association "remove question", f, class: "btn btn-danger btn-sm" %>
  <hr>
</div>

app/views/surveys/_survey_question_tick_fields.html.erb
<div class="tick_fields row no-gutter">
  <%= f.input :value, wrapper_html: { class: "col-xs-6" }, label: "Input tick value" %>
  <%= f.input :label, wrapper_html: { class: "col-xs-6" }, label: "Input tick label" %>
</div>

app/views/surveys/_survey_rating_question_fields.html.erb
<div class='nested-fields'>
  <h3><%= f.object.type.titleize %></h3>
  <div class="form-inputs well">
    <%= f.input :title, label: "Input component title" %>
    <%= f.input :body, label: "Input component description" %>
    <div class="row no-gutter">
      <%= f.input :min, wrapper_html: {class: "col-md-4"}, label: "Minimum value" %>
      <%= f.input :max, wrapper_html: {class: "col-md-4"}, label: "Maximum value" %>
      <%= f.input :step, wrapper_html: {class: "col-md-4"},
                                       input_html: {value: f.object.try(:step) || 1},
                                       label: "Minimum increment" %>
    </div>
    <div class="survey_question_ticks">
        <%= f.simple_fields_for :survey_question_ticks do |tick| %>
          <%= render "survey_question_tick_fields", f: tick %>
        <% end %>
        <div class="links btn-group role="group"">
          <%= link_to_add_association 'add tick', f, :survey_question_ticks,
                                              class: "btn btn-default btn-sm" %>
          <%= link_to_remove_association 'clear ticks', f,
                                              wrapper_class: '.tick_fields',
                                              class: 'btn btn-default btn-sm' %>
        </div>
    </div>
  </div>

  <%= link_to_remove_association "remove question", f, class: "btn btn-danger btn-sm" %>
  <hr>
</div>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'All Surveys', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Created By</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <div>
            <td><%= survey.title %></td>
            <td><%= survey.user.try(:email) %></td>
          </div>
          <td class="col-md-4 text-right">
            <span><%= link_to 'Take', new_survey_survey_submission_path(survey) %> |</span>
            <span><%= link_to 'Show', survey %> |</span>
            <span><%= link_to 'Completed Surveys', survey_survey_submissions_path(survey) %> |</span>
            <span><%= link_to 'Edit', edit_survey_path(survey) %> |</span>
            <span><%= link_to 'Delete', survey, method: :delete, data: { confirm: 'Are you sure?' } %> </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'All Surveys', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @survey.title %></h2>

<p>
  <strong>Created by:</strong>
  <%= @survey.user.email %>
</p>

<div id="survey_questions">
    <% @survey.survey_questions.each do |question| %>
      <h4><%= question.title %></h4>
      <p><%= question.body %></p>
      <hr/>
    <% end %>
</div>

<%= link_to 'Take', new_survey_survey_submission_path(@survey) %> |
<%= link_to 'Completed Surveys', survey_survey_submissions_path(@survey) %> |
<%= link_to 'All Surveys', surveys_path %> |
<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Delete', @survey, method: :delete, data: { confirm: 'Are you sure?' } %>